In [1]:
def test():
    print(' Test() for function')
    return
test()


 Test() for function


In [2]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj= Demo()   ## object creation
obj.test()    ## call for method


test() for the class and method


In [3]:
class Demo1:
    def fact(self,n):
        ## rerurn the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
        
       
p1=Demo1()
print(p1.fact(5))

120


In [4]:

class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [45]:
## Sites Inheritance
class person():
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
## Derived CLass 
class Employee(person):
    def isEmployee(self):
        return True
emp = person("Akash")
emp2=Employee("nikki")
emp1 = person("netflix ")
print(emp.getName(),emp.isEmployee())
print(emp1.getName(),emp1.isEmployee())
emp = person("kanni")
print(emp.getName(),emp.isEmployee())
print(emp2.getName(),emp2.isEmployee())

Akash False
netflix  False
kanni False
nikki True


In [1]:

import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(lst)

[1, 2, 3, 4]


In [2]:
lst= [1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [3]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a1= np.array([1,2,3])
a2= np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [7]:
A=np.matrix(np.ones(4,4),dtype=np.int(64))
print(A)

NameError: name 'np' is not defined

In [15]:
import numpy as np
np.arange(1,10)







array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [28]:
a1=np.array([(1,2,3),(4,5,6)])
print("sliceing last colum:",a1[:,2])

sliceing last colum: [3 6]


In [21]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [30]:
# indexing and sliceing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [32]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1)

first row: [[1 2 3]
 [4 5 6]]


In [39]:
a1=np.array([(1,2,3)]) 
a2=np.array([(4,5,6)])
print("first row:",a1)
print("secound row:",a2)            

first row: [[1 2 3]]
secound row: [[4 5 6]]


In [41]:
a1=np.random.normal(5,1,10)
print(a1)
print("minimum value",np.min(a1))
print("maximum value",np.min(a1))
print("mean value",np.min(a1))
print("mean value",np.min(a1))

[6.21125603 5.58678997 5.85912652 5.96575078 6.62582192 5.77437709
 4.44971641 6.38342068 5.32001187 5.26568945]
minimum value 4.449716406835197
maximum value 4.449716406835197
mean value 4.449716406835197
mean value 4.449716406835197


In [43]:
## multiply of id array
## nump.dot(x,y)
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [3]:
import pandas as pd
dict ={"Name":["nikhil","Anil","DInesh","Harsha","Ajay","Kranth"],
       "EmailID=":["akhil@gmail.com","Anil@gmail.com","dinesh@gmail.com","harsha@gmail.com","Ajay@gmail.com","Kranth@gmail.com"],
       "MobileNumber":[999,888,777,666,555,444],
       "Address":["Hyd","Hyd","Hyd","hyd","Hyd","Hyd"] }
b=pd.DataFrame(dict)
b.index=["01","02","03","04","05","06"]
print(b)



      Name          EmailID=  MobileNumber Address
01  nikhil   akhil@gmail.com           999     Hyd
02    Anil    Anil@gmail.com           888     Hyd
03  DInesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           666     hyd
05    Ajay    Ajay@gmail.com           555     Hyd
06  Kranth  Kranth@gmail.com           444     Hyd


In [4]:
import calendar
a=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [5]:
import akash dateofbirth
a=akash dateofbirth.parcal(2019)

SyntaxError: invalid syntax (<ipython-input-5-a96ab0857430>, line 1)

In [6]:
def check(s1, s2): 
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2) 

The strings are anagrams.
